server:
  port: 1234
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.115.20.174:6006/springcloud?useUnicode=true
#    username: root
#    password: rootpassword
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #ephemeral: false
        #namespace: f48a70b5-2ccc-454d-9098-af0b4a75751f
    sentinel:
      transport:
        dashboard: localhost:8858
seata:
  service:
    vgroup-mapping:
      book-service-seata-service-group: default
    grouplist:
      default: localhost:8868

