server:
  port: 1234

spring:
  application:
    name: bookservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.20.174:6006/springcloud
    username: root
    password: rootpassword
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.134.87:8848

