server:
  port: 1235
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
      #block-page: /blocked
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
        #cluster-name: A
        #namespace: f48a70b5-2ccc-454d-9098-af0b4a75751f
    loadbalancer:
      ribbon:
        enabled: false
      nacos:
        enabled: true
