server:
  port: 1236
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
        #namespace: 5de095b8-bae0-427b-919a-3d65b8beba6b
security:
  oauth2:
    client:
      client-id: web
      client-secret: 654321
      access-token-uri: http://localhost:8500/sso/auth/token
      user-authorization-uri: http://localhost:8500/sso/auth/authorize
    resource:
      token-info-uri: http://loccalhost:8500/sso/auth/check_token